const wikipediaImage = filePath => filePath;

export const STADIUMS = [
  {
    id: 'mexico-city',
    name: 'Estadio Azteca',
    tournamentName: 'Mexico City Stadium',
    city: 'Mexico City',
    municipality: 'Coyoacan',
    country: 'Mexico',
    countryCode: 'MEX',
    region: 'Central',
    capacity: 80824,
    opened: '1966',
    coordinates: { lat: 19.3031, lon: -99.1506 },
    roof: 'open',
    surface: 'hybrid grass',
    aliases: ['Estadio Azteca', 'Estadio Banorte', 'Mexico City Stadium'],
    image: wikipediaImage('https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Vista_a%C3%A9rea_del_Estadio_Azteca_-_2026_-_02.jpg/960px-Vista_a%C3%A9rea_del_Estadio_Azteca_-_2026_-_02.jpg'),
    wiki: 'https://en.wikipedia.org/wiki/Estadio_Azteca',
    summary: 'Najbardziej historyczny obiekt tej edycji: scena mundiali 1970 i 1986, położona wysoko nad miastem i przebudowana przed turniejem 2026.',
    facts: ['pierwszy stadion z trzema mundialami', 'mecz otwarcia 2026', 'dom reprezentacji Meksyku'],
  },
  {
    id: 'new-york-new-jersey',
    name: 'MetLife Stadium',
    tournamentName: 'New York New Jersey Stadium',
    city: 'New York/New Jersey',
    municipality: 'East Rutherford, New Jersey',
    country: 'USA',
    countryCode: 'USA',
    region: 'Eastern',
    capacity: 80663,
    opened: '2010',
    coordinates: { lat: 40.8135, lon: -74.0744 },
    roof: 'open',
    surface: 'temporary grass',
    aliases: ['MetLife Stadium', 'New York New Jersey Stadium'],
    image: wikipediaImage('https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Metlife_stadium_%28Aerial_view%29.jpg/960px-Metlife_stadium_%28Aerial_view%29.jpg'),
    wiki: 'https://en.wikipedia.org/wiki/MetLife_Stadium',
    summary: 'Największa scena finałowa w rejonie Nowego Jorku, zbudowana dla dwóch klubów NFL i przebudowana pod naturalną murawę FIFA.',
    facts: ['finał 19 lipca', 'dom Giants i Jets', 'najdroższy stadion USA w chwili otwarcia'],
  },
  {
    id: 'dallas',
    name: 'AT&T Stadium',
    tournamentName: 'Dallas Stadium',
    city: 'Dallas',
    municipality: 'Arlington, Texas',
    country: 'USA',
    countryCode: 'USA',
    region: 'Central',
    capacity: 70649,
    opened: '2009',
    coordinates: { lat: 32.7478, lon: -97.0928 },
    roof: 'retractable',
    surface: 'temporary grass',
    aliases: ['AT&T Stadium', 'Dallas Stadium'],
    image: wikipediaImage('https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Arlington_June_2020_4_%28AT%26T_Stadium%29.jpg/960px-Arlington_June_2020_4_%28AT%26T_Stadium%29.jpg'),
    wiki: 'https://en.wikipedia.org/wiki/AT%26T_Stadium',
    summary: 'Gigant z rozsuwanym dachem i monumentalnym ekranem nad boiskiem, jedna z najbardziej widowiskowych aren turnieju.',
    facts: ['najwięcej meczów w turnieju', 'rozsuwany dach', 'dom Dallas Cowboys'],
  },
  {
    id: 'los-angeles',
    name: 'SoFi Stadium',
    tournamentName: 'Los Angeles Stadium',
    city: 'Los Angeles',
    municipality: 'Inglewood, California',
    country: 'USA',
    countryCode: 'USA',
    region: 'Western',
    capacity: 70492,
    opened: '2020',
    coordinates: { lat: 33.953, lon: -118.339 },
    roof: 'translucent',
    surface: 'temporary grass',
    aliases: ['SoFi Stadium', 'Los Angeles Stadium'],
    image: wikipediaImage('https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/SoFi_Stadium_2023.jpg/960px-SoFi_Stadium_2023.jpg'),
    wiki: 'https://en.wikipedia.org/wiki/SoFi_Stadium',
    summary: 'Futurystyczna arena w Inglewood, pod półprzezroczystym dachem i z ogromnym kompleksem rozrywkowym wokół stadionu.',
    facts: ['półprzezroczysty dach', 'kompleks Hollywood Park', 'dom Rams i Chargers'],
  },
  {
    id: 'kansas-city',
    name: 'GEHA Field at Arrowhead Stadium',
    tournamentName: 'Kansas City Stadium',
    city: 'Kansas City',
    municipality: 'Kansas City, Missouri',
    country: 'USA',
    countryCode: 'USA',
    region: 'Central',
    capacity: 69045,
    opened: '1972',
    coordinates: { lat: 39.0489, lon: -94.4839 },
    roof: 'open',
    surface: 'temporary grass',
    aliases: ['GEHA Field at Arrowhead Stadium', 'Arrowhead Stadium', 'Kansas City Stadium'],
    image: wikipediaImage('https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Aerial_view_of_Arrowhead_Stadium_08-31-2013.jpg/960px-Aerial_view_of_Arrowhead_Stadium_08-31-2013.jpg'),
    wiki: 'https://en.wikipedia.org/wiki/Arrowhead_Stadium',
    summary: 'Jedna z najgłośniejszych aren futbolu amerykańskiego, z klasyczną misą trybun i wyjątkowo zwartą atmosferą.',
    facts: ['legendarna akustyka', 'dom Kansas City Chiefs', 'otwarty stadion'],
  },
  {
    id: 'sf-bay-area',
    name: "Levi's Stadium",
    tournamentName: 'San Francisco Bay Area Stadium',
    city: 'San Francisco Bay Area',
    municipality: 'Santa Clara, California',
    country: 'USA',
    countryCode: 'USA',
    region: 'Western',
    capacity: 68827,
    opened: '2014',
    coordinates: { lat: 37.403, lon: -121.97 },
    roof: 'open',
    surface: 'temporary grass',
    aliases: ["Levi's Stadium", 'San Francisco Bay Area Stadium'],
    image: wikipediaImage('https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Levi%27s_Stadium_in_February_2016_prior_to_Super_Bowl_50_%2824398261729%29.jpg/960px-Levi%27s_Stadium_in_February_2016_prior_to_Super_Bowl_50_%2824398261729%29.jpg'),
    wiki: "https://en.wikipedia.org/wiki/Levi's_Stadium",
    summary: 'Nowoczesna arena w Santa Clara, położona przy południowym krańcu zatoki, około 40 mil od San Francisco.',
    facts: ['Super Bowl 50', 'dom 49ers', 'arena Bay Area'],
  },
  {
    id: 'houston',
    name: 'NRG Stadium',
    tournamentName: 'Houston Stadium',
    city: 'Houston',
    municipality: 'Houston, Texas',
    country: 'USA',
    countryCode: 'USA',
    region: 'Central',
    capacity: 68777,
    opened: '2002',
    coordinates: { lat: 29.6847, lon: -95.4108 },
    roof: 'retractable',
    surface: 'temporary grass',
    aliases: ['NRG Stadium', 'Houston Stadium'],
    image: wikipediaImage('https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Nrg_stadium.jpg/960px-Nrg_stadium.jpg'),
    wiki: 'https://en.wikipedia.org/wiki/NRG_Stadium',
    summary: 'Pierwszy stadion NFL z rozsuwanym dachem, przygotowany na upalne mecze w Teksasie i turniejową murawę.',
    facts: ['rozsuwany dach', 'dom Houston Texans', 'pierwszy taki dach w NFL'],
  },
  {
    id: 'philadelphia',
    name: 'Lincoln Financial Field',
    tournamentName: 'Philadelphia Stadium',
    city: 'Philadelphia',
    municipality: 'Philadelphia, Pennsylvania',
    country: 'USA',
    countryCode: 'USA',
    region: 'Eastern',
    capacity: 68324,
    opened: '2003',
    coordinates: { lat: 39.9008, lon: -75.1675 },
    roof: 'open',
    surface: 'temporary grass',
    aliases: ['Lincoln Financial Field', 'Philadelphia Stadium'],
    image: wikipediaImage('https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Lincoln_Financial_Field_%28Aerial_view%29.jpg/960px-Lincoln_Financial_Field_%28Aerial_view%29.jpg'),
    wiki: 'https://en.wikipedia.org/wiki/Lincoln_Financial_Field',
    summary: 'Stadion w południowym kompleksie sportowym Filadelfii, z prostą, stromą bryłą i bardzo blisko położonymi trybunami.',
    facts: ['kompleks South Philadelphia', 'dom Eagles', 'otwarty stadion'],
  },
  {
    id: 'atlanta',
    name: 'Mercedes-Benz Stadium',
    tournamentName: 'Atlanta Stadium',
    city: 'Atlanta',
    municipality: 'Atlanta, Georgia',
    country: 'USA',
    countryCode: 'USA',
    region: 'Eastern',
    capacity: 68239,
    opened: '2017',
    coordinates: { lat: 33.7556, lon: -84.4 },
    roof: 'retractable',
    surface: 'temporary grass',
    aliases: ['Mercedes-Benz Stadium', 'Atlanta Stadium'],
    image: wikipediaImage('https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Mercedes_Benz_Stadium_time_lapse_capture_2017-08-13.jpg/960px-Mercedes_Benz_Stadium_time_lapse_capture_2017-08-13.jpg'),
    wiki: 'https://en.wikipedia.org/wiki/Mercedes-Benz_Stadium',
    summary: 'Arena ze składanym dachem i charakterystycznym pierścieniowym ekranem, używana na co dzień przez Falcons i Atlanta United.',
    facts: ['rozsuwany dach', 'pierścieniowy ekran', 'dom Atlanta United'],
  },
  {
    id: 'seattle',
    name: 'Lumen Field',
    tournamentName: 'Seattle Stadium',
    city: 'Seattle',
    municipality: 'Seattle, Washington',
    country: 'USA',
    countryCode: 'USA',
    region: 'Western',
    capacity: 66925,
    opened: '2002',
    coordinates: { lat: 47.5952, lon: -122.3316 },
    roof: 'partial',
    surface: 'temporary grass',
    aliases: ['Lumen Field', 'Seattle Stadium'],
    image: wikipediaImage('https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/2025_FIFA_Club_World_Cup_-_Seattle_Sounders_FC_vs._Atl%C3%A9tico_Madrid_-_05.jpg/960px-2025_FIFA_Club_World_Cup_-_Seattle_Sounders_FC_vs._Atl%C3%A9tico_Madrid_-_05.jpg'),
    wiki: 'https://en.wikipedia.org/wiki/Lumen_Field',
    summary: 'Położony tuż przy centrum Seattle stadion z otwartymi bokami i częściowym zadaszeniem, znany z intensywnego dopingu.',
    facts: ['centrum Seattle', 'dom Sounders i Seahawks', 'częściowy dach'],
  },
  {
    id: 'miami',
    name: 'Hard Rock Stadium',
    tournamentName: 'Miami Stadium',
    city: 'Miami',
    municipality: 'Miami Gardens, Florida',
    country: 'USA',
    countryCode: 'USA',
    region: 'Eastern',
    capacity: 64478,
    opened: '1987',
    coordinates: { lat: 25.9581, lon: -80.2389 },
    roof: 'canopy',
    surface: 'temporary grass',
    aliases: ['Hard Rock Stadium', 'Miami Stadium'],
    image: wikipediaImage('https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Hard_Rock_Stadium_for_Super_Bowl_LIV_%2849606710103%29.jpg/960px-Hard_Rock_Stadium_for_Super_Bowl_LIV_%2849606710103%29.jpg'),
    wiki: 'https://en.wikipedia.org/wiki/Hard_Rock_Stadium',
    summary: 'Stadion w Miami Gardens z charakterystyczną osłoną trybun, gotowy na tropikalne tempo późnej fazy turnieju.',
    facts: ['mecz o 3. miejsce', 'dom Miami Dolphins', 'zadaszone trybuny'],
  },
  {
    id: 'boston',
    name: 'Gillette Stadium',
    tournamentName: 'Boston Stadium',
    city: 'Boston',
    municipality: 'Foxborough, Massachusetts',
    country: 'USA',
    countryCode: 'USA',
    region: 'Eastern',
    capacity: 64146,
    opened: '2002',
    coordinates: { lat: 42.091, lon: -71.264 },
    roof: 'open',
    surface: 'temporary grass',
    aliases: ['Gillette Stadium', 'Boston Stadium'],
    image: wikipediaImage('https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Gillette_Stadium_%28Top_View%29.jpg/960px-Gillette_Stadium_%28Top_View%29.jpg'),
    wiki: 'https://en.wikipedia.org/wiki/Gillette_Stadium',
    summary: 'Podmiejska arena między Bostonem i Providence, wspólna baza New England Patriots oraz New England Revolution.',
    facts: ['Foxborough', 'dom Patriots i Revolution', 'otwarty stadion'],
  },
  {
    id: 'vancouver',
    name: 'BC Place',
    tournamentName: 'BC Place Vancouver',
    city: 'Vancouver',
    municipality: 'Vancouver, British Columbia',
    country: 'Canada',
    countryCode: 'CAN',
    region: 'Western',
    capacity: 52497,
    opened: '1983',
    coordinates: { lat: 49.2767, lon: -123.1119 },
    roof: 'retractable',
    surface: 'temporary grass',
    aliases: ['BC Place', 'BC Place Vancouver'],
    image: wikipediaImage('https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/BC_Place_2015_Women%27s_FIFA_World_Cup.jpg/960px-BC_Place_2015_Women%27s_FIFA_World_Cup.jpg'),
    wiki: 'https://en.wikipedia.org/wiki/BC_Place',
    summary: 'Kanadyjski stadion z rozsuwanym dachem nad False Creek, przebudowany po Zimowych Igrzyskach i gotowy na mundialową murawę.',
    facts: ['rozsuwany dach', 'False Creek', 'arena igrzysk 2010'],
  },
  {
    id: 'monterrey',
    name: 'Estadio BBVA',
    tournamentName: 'Estadio Monterrey',
    city: 'Monterrey',
    municipality: 'Guadalupe, Nuevo Leon',
    country: 'Mexico',
    countryCode: 'MEX',
    region: 'Central',
    capacity: 51243,
    opened: '2015',
    coordinates: { lat: 25.6692, lon: -100.2444 },
    roof: 'partial',
    surface: 'grass',
    aliases: ['Estadio BBVA', 'Estadio Monterrey'],
    image: wikipediaImage('https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Mexico_Guadalupe_Monterrey_Estadio_BBVA_Bancomer_fifa_world_cup_2026_6.JPG/960px-Mexico_Guadalupe_Monterrey_Estadio_BBVA_Bancomer_fifa_world_cup_2026_6.JPG'),
    wiki: 'https://en.wikipedia.org/wiki/Estadio_BBVA',
    summary: 'El Gigante de Acero stoi u podnóża Cerro de la Silla i jest jedną z najbardziej malowniczych aren turnieju.',
    facts: ['widok na Cerro de la Silla', 'dom CF Monterrey', 'piłkarski stadion'],
  },
  {
    id: 'guadalajara',
    name: 'Estadio Akron',
    tournamentName: 'Estadio Guadalajara',
    city: 'Guadalajara',
    municipality: 'Zapopan, Jalisco',
    country: 'Mexico',
    countryCode: 'MEX',
    region: 'Central',
    capacity: 45664,
    opened: '2010',
    coordinates: { lat: 20.6817, lon: -103.4628 },
    roof: 'open',
    surface: 'grass',
    aliases: ['Estadio Akron', 'Estadio Guadalajara'],
    image: wikipediaImage('https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Estadio_Akron_02-07-2022_cabecera_sur_lado_derecho_%283%29.jpg/960px-Estadio_Akron_02-07-2022_cabecera_sur_lado_derecho_%283%29.jpg'),
    wiki: 'https://en.wikipedia.org/wiki/Estadio_Akron',
    summary: 'Dom Chivas w Zapopan, zaprojektowany jak stadion wbudowany w zielony pagórek na zachód od Guadalajary.',
    facts: ['dom Chivas', 'Zapopan', 'piłkarski stadion'],
  },
  {
    id: 'toronto',
    name: 'BMO Field',
    tournamentName: 'Toronto Stadium',
    city: 'Toronto',
    municipality: 'Toronto, Ontario',
    country: 'Canada',
    countryCode: 'CAN',
    region: 'Eastern',
    capacity: 43036,
    opened: '2007',
    coordinates: { lat: 43.6333, lon: -79.4186 },
    roof: 'partial',
    surface: 'grass',
    aliases: ['BMO Field', 'Toronto Stadium'],
    image: wikipediaImage('https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Toronto_BMO_Field_in_2024.jpg/960px-Toronto_BMO_Field_in_2024.jpg'),
    wiki: 'https://en.wikipedia.org/wiki/BMO_Field',
    summary: 'Najmniejszy obiekt turnieju, rozbudowany pod mundial na Exhibition Place, bardzo blisko jeziora Ontario.',
    facts: ['rozbudowa pod 2026', 'dom Toronto FC', 'nad jeziorem Ontario'],
  },
];

export const STADIUM_COUNTRIES = [
  { id: 'all', label: 'Wszystkie' },
  { id: 'USA', label: 'USA' },
  { id: 'Mexico', label: 'Meksyk' },
  { id: 'Canada', label: 'Kanada' },
];

const normalizeVenue = value => String(value || '')
  .normalize('NFD')
  .replace(/[\u0300-\u036f]/g, '')
  .toLowerCase()
  .replace(/&/g, 'and')
  .replace(/[^a-z0-9]+/g, ' ')
  .trim();

const ALIAS_TO_STADIUM = new Map(
  STADIUMS.flatMap(stadium => stadium.aliases.map(alias => [normalizeVenue(alias), stadium.id]))
);

export function findStadiumByVenue(venue) {
  const name = normalizeVenue(typeof venue === 'string' ? venue : venue?.name);
  const id = ALIAS_TO_STADIUM.get(name);
  return id ? STADIUMS.find(stadium => stadium.id === id) : null;
}

export function getStadiumById(id) {
  return STADIUMS.find(stadium => stadium.id === id) || null;
}

export function stadiumMatches(data, stadiumId) {
  const matches = data?.matches || [];
  return matches
    .filter(match => findStadiumByVenue(match.venue)?.id === stadiumId)
    .slice()
    .sort((a, b) => new Date(a.date) - new Date(b.date));
}

export function enrichStadiums(data) {
  return STADIUMS.map(stadium => {
    const matches = stadiumMatches(data, stadium.id);
    const completed = matches.filter(match => match.status?.completed);
    const live = matches.filter(match => match.status?.state === 'in');
    const upcoming = matches.filter(match => !match.status?.completed && match.status?.state !== 'in');
    const attendanceValues = completed
      .map(match => match.attendance || 0)
      .filter(value => value > 0);
    const totalAttendance = attendanceValues.reduce((sum, value) => sum + value, 0);

    return {
      ...stadium,
      matches,
      matchCount: matches.length,
      completedCount: completed.length,
      liveCount: live.length,
      upcomingCount: upcoming.length,
      nextMatch: live[0] || upcoming[0] || null,
      totalAttendance,
      avgAttendance: attendanceValues.length ? Math.round(totalAttendance / attendanceValues.length) : null,
      maxAttendance: attendanceValues.length ? Math.max(...attendanceValues) : null,
    };
  });
}

export function stadiumTotals(data) {
  const stadiums = enrichStadiums(data);
  return {
    count: stadiums.length,
    countries: new Set(stadiums.map(stadium => stadium.country)).size,
    capacity: stadiums.reduce((sum, stadium) => sum + stadium.capacity, 0),
    matches: stadiums.reduce((sum, stadium) => sum + stadium.matchCount, 0),
  };
}
